# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 21, 10, 6, 41, 575958, tzinfo=utc), verbose_name='Date added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commodity',
            name='modify_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 5, 21, 10, 6, 50, 681359, tzinfo=utc), verbose_name='Date modified'),
            preserve_default=False,
        ),
    ]
