# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160521_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='color',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='size',
            name='priority',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Priority'),
        ),
    ]
