# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-21 08:50
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.City', verbose_name='City')),
            ],
            options={
                'verbose_name': 'Districts',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='Title')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores', verbose_name='Logo')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('build_name', models.CharField(max_length=50, verbose_name='Building name')),
                ('build_no', models.CharField(max_length=5, verbose_name='Building number')),
                ('apt', models.CharField(max_length=5, verbose_name='Apartments')),
                ('brand', models.CharField(max_length=50, verbose_name='Brand')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.District', verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='vendors', verbose_name='Avatar')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Store', verbose_name='Store')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.State', verbose_name='State'),
        ),
    ]
